import { expect, test } from "bun:test";
import { buildGuardHooks, type PhaseGuards } from "./guardHooks.js";

const cwd = "/repo/worktree";
async function decision(guards: PhaseGuards, tool: string, toolInput: Record<string, unknown>) { const hooks = buildGuardHooks({ guards, phaseCwd: cwd }).PreToolUse ?? []; const matcher = hooks.find((entry) => entry.matcher?.split("|").includes(tool)); if (!matcher) return undefined; const results = await Promise.all(matcher.hooks.map((hook) => hook({ hook_event_name: "PreToolUse", tool_name: tool, tool_input: toolInput, session_id: "s", transcript_path: "", cwd } as never, undefined, { signal: new AbortController().signal }))); return results.map((result) => result as { hookSpecificOutput?: { permissionDecision?: string } }).find((result) => result.hookSpecificOutput?.permissionDecision === "deny")?.hookSpecificOutput?.permissionDecision; }

test("read_only denies file writes inside the workspace", async () => { expect(await decision({ readOnly: true }, "Edit", { file_path: "src/a.ts" })).toBe("deny"); expect(await decision({ readOnly: true }, "Edit", { file_path: "/tmp/a.ts" })).toBeUndefined(); });
test("no_git_history denies history changes but allows inspection", async () => { expect(await decision({ noGitHistory: true }, "Bash", { command: "git commit -m x" })).toBe("deny"); expect(await decision({ noGitHistory: true }, "Bash", { command: "git status" })).toBeUndefined(); });
test("no_forge_effects denies forge writes but allows reads", async () => { expect(await decision({ noForgeEffects: true }, "Bash", { command: "gh pr create --draft" })).toBe("deny"); expect(await decision({ noForgeEffects: true }, "Bash", { command: "gh pr \"close\" 42" })).toBe("deny"); expect(await decision({ noForgeEffects: true }, "Bash", { command: "gh api repos/o/r --method=DELETE" })).toBe("deny"); expect(await decision({ noForgeEffects: true }, "Bash", { command: "gh api repos/o/r --method GET -f state=open" })).toBeUndefined(); expect(await decision({ noForgeEffects: true }, "Bash", { command: "gh api repos/o/r --method GET && gh api repos/o/r/issues --method POST" })).toBe("deny"); expect(await decision({ noForgeEffects: true }, "Bash", { command: "gh api repos/o/r --method GET; gh api repos/o/r/issues -f title=x" })).toBe("deny"); expect(await decision({ noForgeEffects: true }, "Bash", { command: "gh pr view 42" })).toBeUndefined(); });
test("empty guards install no hooks", () => { expect(buildGuardHooks({ guards: {}, phaseCwd: cwd })).toEqual({}); });
